// models/Recipe.js
// Defines the structure of a "Recipe" document — the core entity of the entire app.

const mongoose = require("mongoose");

// A sub-schema for ingredients. This is NOT a separate collection —
// it lives embedded directly inside each recipe document, since ingredients
// only ever make sense in the context of their specific recipe.
const ingredientSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Ingredient name is required"],
      trim: true,
    },
    quantity: {
      type: String, // stored as string to allow values like "1/2", "a pinch", "2-3"
      required: [true, "Ingredient quantity is required"],
    },
    unit: {
      type: String, // e.g., "grams", "cups", "tbsp"
      trim: true,
      default: "",
    },
  },
  { _id: false } // we don't need a separate ID for each ingredient sub-document
);

// A sub-schema for step-by-step instructions
const instructionStepSchema = new mongoose.Schema(
  {
    stepNumber: {
      type: Number,
      required: true,
    },
    description: {
      type: String,
      required: [true, "Step description is required"],
      trim: true,
    },
    image: {
      type: String, // optional image for this specific step
      default: "",
    },
  },
  { _id: false }
);

const recipeSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, "Recipe title is required"],
      trim: true,
      minlength: [3, "Title must be at least 3 characters"],
      maxlength: [100, "Title cannot exceed 100 characters"],
    },

    slug: {
      type: String,
      unique: true,
      lowercase: true,
    },

    description: {
      type: String,
      required: [true, "Recipe description is required"],
      trim: true,
      maxlength: [500, "Description cannot exceed 500 characters"],
    },

    images: {
      type: [String], // array of Cloudinary URLs
      default: [],
    },

    // Who created this recipe — links to the User model
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Was this generated by AI, or written by a human user?
    source: {
      type: String,
      enum: ["user", "ai"],
      default: "user",
    },

    ingredients: {
      type: [ingredientSchema],
      required: true,
      validate: {
        validator: (arr) => arr.length > 0,
        message: "A recipe must have at least one ingredient",
      },
    },

    instructions: {
      type: [instructionStepSchema],
      required: true,
      validate: {
        validator: (arr) => arr.length > 0,
        message: "A recipe must have at least one instruction step",
      },
    },

    // Classification — links to Category model, can have multiple
    // (e.g., a recipe can be both "Indian" cuisine AND "Vegan" diet AND "Dinner" mealType)
    categories: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Category",
      },
    ],

    cuisine: {
      type: String,
      trim: true,
      default: "",
    },

    mealType: {
      type: String,
      enum: ["breakfast", "lunch", "dinner", "snack", "dessert", "drink"],
    },

    dietType: {
      type: [String], // a recipe can be BOTH "vegetarian" AND "gluten-free", so it's an array
      enum: ["vegetarian", "vegan", "non-vegetarian", "gluten-free", "dairy-free", "keto", "low-carb"],
      default: [],
    },

    allergens: {
      type: [String], // e.g., ["nuts", "dairy", "shellfish"] — used to WARN users, opposite of dietType
      default: [],
    },

    difficulty: {
      type: String,
      enum: ["easy", "medium", "hard"],
      default: "medium",
    },

    prepTime: {
      type: Number, // in minutes
      required: [true, "Prep time is required"],
      min: [0, "Prep time cannot be negative"],
    },

    cookTime: {
      type: Number, // in minutes
      required: [true, "Cook time is required"],
      min: [0, "Cook time cannot be negative"],
    },

    servings: {
      type: Number,
      required: [true, "Servings is required"],
      min: [1, "Servings must be at least 1"],
    },

    // Nutrition — per serving
    nutrition: {
      calories: { type: Number, default: 0, min: 0 },
      protein: { type: Number, default: 0, min: 0 }, // grams
      carbs: { type: Number, default: 0, min: 0 }, // grams
      fat: { type: Number, default: 0, min: 0 }, // grams
      fiber: { type: Number, default: 0, min: 0 }, // grams
      sugar: { type: Number, default: 0, min: 0 }, // grams
    },

    // Approximate cost tier, used for "Search by Budget"
    budget: {
      type: String,
      enum: ["low", "medium", "high"],
      default: "medium",
    },

    tags: {
      type: [String], // free-form searchable tags, e.g. ["quick", "kid-friendly", "one-pot"]
      default: [],
    },

    // Aggregated rating data — we STORE these as numbers on the recipe itself
    // (instead of calculating live from all reviews every time) for performance.
    // We'll update these automatically whenever a review is added/removed (Phase 4).
    averageRating: {
      type: Number,
      default: 0,
      min: 0,
      max: 5,
    },
    numReviews: {
      type: Number,
      default: 0,
    },

    views: {
      type: Number,
      default: 0,
    },

    favoritesCount: {
      type: Number,
      default: 0,
    },

    isPublished: {
      type: Boolean,
      default: true, // false = draft, not shown publicly yet
    },
  },
  { timestamps: true }
);

// A "text index" allows MongoDB to efficiently search across these fields
// using natural language queries (used later for our search feature)
recipeSchema.index({ title: "text", description: "text", tags: "text" });

module.exports = mongoose.model("Recipe", recipeSchema);